### ISSUE TITLE
Fix name of 2015_08_27_082906_create_saveComtent_table.php.

### ISSUE THREAD

**Issue by john29917958** [john29917958/Laravel-Message-Board#29]
Try to rename `2015_08_27_082906_create_saveComtent_table.php` to `08_27_082906_create_message_board_table.php`.

Also, please rename the class name from `CreateSaveComtentTable` to `CreateMessageBoardTable`.

It will be more instinctive.

**Comment by LittleTina** [comment]
Please refer to #30.
